/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TProtocolFactory.h"
#import "TBaseClient.h"


enum TTGResponseState {
  ResponseState_StateOk = 200,
  ResponseState_StateError = 201,
  ResponseState_StateEmpty = 202
};

enum TTGSaleType {
  SaleType_SaleTypeRegular = 0,
  SaleType_SaleTypeFastFood = 1,
  SaleType_SaleTypeTakeAway = 2,
  SaleType_SaleTypeStore = 3
};

enum TTGTakeAwayType {
  TakeAwayType_TakeAwayTypePhone = 0,
  TakeAwayType_TakeAwayTypeBaidu = 1,
  TakeAwayType_TakeAwayTypeEleme = 2,
  TakeAwayType_TakeAwayTypeKoubei = 3,
  TakeAwayType_TakeAwayTypeMeituan = 4
};

@interface TTGDailyDataForSale : NSObject <TBase, NSCoding> {
  int __type;
  NSString * __name;
  int32_t __countD;
  double __sales;

  BOOL __type_isset;
  BOOL __name_isset;
  BOOL __countD_isset;
  BOOL __sales_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=type, setter=setType:) int type;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=countD, setter=setCountD:) int32_t countD;
@property (nonatomic, getter=sales, setter=setSales:) double sales;
#endif

- (id) init;
- (id) initWithType: (int) type name: (NSString *) name countD: (int32_t) countD sales: (double) sales;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int) type;
- (void) setType: (int) type;
#endif
- (BOOL) typeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (int32_t) countD;
- (void) setCountD: (int32_t) countD;
#endif
- (BOOL) countDIsSet;

#if !__has_feature(objc_arc)
- (double) sales;
- (void) setSales: (double) sales;
#endif
- (BOOL) salesIsSet;

@end

@interface TTGDailyDataForShop : NSObject <TBase, NSCoding> {
  int32_t __sid;
  NSString * __name;
  double __lastSales;
  double __currentSales;

  BOOL __sid_isset;
  BOOL __name_isset;
  BOOL __lastSales_isset;
  BOOL __currentSales_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=sid, setter=setSid:) int32_t sid;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=lastSales, setter=setLastSales:) double lastSales;
@property (nonatomic, getter=currentSales, setter=setCurrentSales:) double currentSales;
#endif

- (id) init;
- (id) initWithSid: (int32_t) sid name: (NSString *) name lastSales: (double) lastSales currentSales: (double) currentSales;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) sid;
- (void) setSid: (int32_t) sid;
#endif
- (BOOL) sidIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (double) lastSales;
- (void) setLastSales: (double) lastSales;
#endif
- (BOOL) lastSalesIsSet;

#if !__has_feature(objc_arc)
- (double) currentSales;
- (void) setCurrentSales: (double) currentSales;
#endif
- (BOOL) currentSalesIsSet;

@end

@interface TTGDailyDataForCompany : NSObject <TBase, NSCoding> {
  double __lastTotalSales;
  double __currentTotalSales;
  NSMutableArray * __dailyTotalDataForCompany;

  BOOL __lastTotalSales_isset;
  BOOL __currentTotalSales_isset;
  BOOL __dailyTotalDataForCompany_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=lastTotalSales, setter=setLastTotalSales:) double lastTotalSales;
@property (nonatomic, getter=currentTotalSales, setter=setCurrentTotalSales:) double currentTotalSales;
@property (nonatomic, retain, getter=dailyTotalDataForCompany, setter=setDailyTotalDataForCompany:) NSMutableArray * dailyTotalDataForCompany;
#endif

- (id) init;
- (id) initWithLastTotalSales: (double) lastTotalSales currentTotalSales: (double) currentTotalSales dailyTotalDataForCompany: (NSMutableArray *) dailyTotalDataForCompany;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (double) lastTotalSales;
- (void) setLastTotalSales: (double) lastTotalSales;
#endif
- (BOOL) lastTotalSalesIsSet;

#if !__has_feature(objc_arc)
- (double) currentTotalSales;
- (void) setCurrentTotalSales: (double) currentTotalSales;
#endif
- (BOOL) currentTotalSalesIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) dailyTotalDataForCompany;
- (void) setDailyTotalDataForCompany: (NSMutableArray *) dailyTotalDataForCompany;
#endif
- (BOOL) dailyTotalDataForCompanyIsSet;

@end

@interface TTGdailyReportRequest_C : NSObject <TBase, NSCoding> {
  NSString * __date;

  BOOL __date_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=date, setter=setDate:) NSString * date;
#endif

- (id) init;
- (id) initWithDate: (NSString *) date;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) date;
- (void) setDate: (NSString *) date;
#endif
- (BOOL) dateIsSet;

@end

@interface TTGdailyReportRequest_S : NSObject <TBase, NSCoding> {
  int __state;
  NSString * __message;
  TTGDailyDataForCompany * __dailyDataForCompany;
  NSMutableArray * __dailyDataForShopList;

  BOOL __state_isset;
  BOOL __message_isset;
  BOOL __dailyDataForCompany_isset;
  BOOL __dailyDataForShopList_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=state, setter=setState:) int state;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, retain, getter=dailyDataForCompany, setter=setDailyDataForCompany:) TTGDailyDataForCompany * dailyDataForCompany;
@property (nonatomic, retain, getter=dailyDataForShopList, setter=setDailyDataForShopList:) NSMutableArray * dailyDataForShopList;
#endif

- (id) init;
- (id) initWithState: (int) state message: (NSString *) message dailyDataForCompany: (TTGDailyDataForCompany *) dailyDataForCompany dailyDataForShopList: (NSMutableArray *) dailyDataForShopList;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int) state;
- (void) setState: (int) state;
#endif
- (BOOL) stateIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

#if !__has_feature(objc_arc)
- (TTGDailyDataForCompany *) dailyDataForCompany;
- (void) setDailyDataForCompany: (TTGDailyDataForCompany *) dailyDataForCompany;
#endif
- (BOOL) dailyDataForCompanyIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) dailyDataForShopList;
- (void) setDailyDataForShopList: (NSMutableArray *) dailyDataForShopList;
#endif
- (BOOL) dailyDataForShopListIsSet;

@end

@interface TTGDailyRankForDish : NSObject <TBase, NSCoding> {
  NSString * __name;
  int32_t __count_D;

  BOOL __name_isset;
  BOOL __count_D_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=count_D, setter=setCount_D:) int32_t count_D;
#endif

- (id) init;
- (id) initWithName: (NSString *) name count_D: (int32_t) count_D;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (int32_t) count_D;
- (void) setCount_D: (int32_t) count_D;
#endif
- (BOOL) count_DIsSet;

@end

@interface TTGDailyRankForPrice : NSObject <TBase, NSCoding> {
  NSString * __name;
  double __totalPrice;

  BOOL __name_isset;
  BOOL __totalPrice_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=totalPrice, setter=setTotalPrice:) double totalPrice;
#endif

- (id) init;
- (id) initWithName: (NSString *) name totalPrice: (double) totalPrice;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (double) totalPrice;
- (void) setTotalPrice: (double) totalPrice;
#endif
- (BOOL) totalPriceIsSet;

@end

@interface TTGDailyRank : NSObject <TBase, NSCoding> {
  NSMutableArray * __dailyRankForSaleGoodList;
  NSMutableArray * __dailyRankForPriceList;
  NSMutableArray * __dailyRankForSaleTerribleList;

  BOOL __dailyRankForSaleGoodList_isset;
  BOOL __dailyRankForPriceList_isset;
  BOOL __dailyRankForSaleTerribleList_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=dailyRankForSaleGoodList, setter=setDailyRankForSaleGoodList:) NSMutableArray * dailyRankForSaleGoodList;
@property (nonatomic, retain, getter=dailyRankForPriceList, setter=setDailyRankForPriceList:) NSMutableArray * dailyRankForPriceList;
@property (nonatomic, retain, getter=dailyRankForSaleTerribleList, setter=setDailyRankForSaleTerribleList:) NSMutableArray * dailyRankForSaleTerribleList;
#endif

- (id) init;
- (id) initWithDailyRankForSaleGoodList: (NSMutableArray *) dailyRankForSaleGoodList dailyRankForPriceList: (NSMutableArray *) dailyRankForPriceList dailyRankForSaleTerribleList: (NSMutableArray *) dailyRankForSaleTerribleList;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) dailyRankForSaleGoodList;
- (void) setDailyRankForSaleGoodList: (NSMutableArray *) dailyRankForSaleGoodList;
#endif
- (BOOL) dailyRankForSaleGoodListIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) dailyRankForPriceList;
- (void) setDailyRankForPriceList: (NSMutableArray *) dailyRankForPriceList;
#endif
- (BOOL) dailyRankForPriceListIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) dailyRankForSaleTerribleList;
- (void) setDailyRankForSaleTerribleList: (NSMutableArray *) dailyRankForSaleTerribleList;
#endif
- (BOOL) dailyRankForSaleTerribleListIsSet;

@end

@interface TTGdailyRankRequest_C : NSObject <TBase, NSCoding> {
  NSString * __date;
  NSString * __sid;
  NSString * __num;

  BOOL __date_isset;
  BOOL __sid_isset;
  BOOL __num_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=date, setter=setDate:) NSString * date;
@property (nonatomic, retain, getter=sid, setter=setSid:) NSString * sid;
@property (nonatomic, retain, getter=num, setter=setNum:) NSString * num;
#endif

- (id) init;
- (id) initWithDate: (NSString *) date sid: (NSString *) sid num: (NSString *) num;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) date;
- (void) setDate: (NSString *) date;
#endif
- (BOOL) dateIsSet;

#if !__has_feature(objc_arc)
- (NSString *) sid;
- (void) setSid: (NSString *) sid;
#endif
- (BOOL) sidIsSet;

#if !__has_feature(objc_arc)
- (NSString *) num;
- (void) setNum: (NSString *) num;
#endif
- (BOOL) numIsSet;

@end

@interface TTGdailyRankRequest_S : NSObject <TBase, NSCoding> {
  int __state;
  NSString * __message;
  TTGDailyRank * __dailyRank;

  BOOL __state_isset;
  BOOL __message_isset;
  BOOL __dailyRank_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=state, setter=setState:) int state;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, retain, getter=dailyRank, setter=setDailyRank:) TTGDailyRank * dailyRank;
#endif

- (id) init;
- (id) initWithState: (int) state message: (NSString *) message dailyRank: (TTGDailyRank *) dailyRank;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int) state;
- (void) setState: (int) state;
#endif
- (BOOL) stateIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

#if !__has_feature(objc_arc)
- (TTGDailyRank *) dailyRank;
- (void) setDailyRank: (TTGDailyRank *) dailyRank;
#endif
- (BOOL) dailyRankIsSet;

@end

@interface TTGTakeAwayInfo : NSObject <TBase, NSCoding> {
  int __type;
  int32_t __countT;
  double __sales;

  BOOL __type_isset;
  BOOL __countT_isset;
  BOOL __sales_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=type, setter=setType:) int type;
@property (nonatomic, getter=countT, setter=setCountT:) int32_t countT;
@property (nonatomic, getter=sales, setter=setSales:) double sales;
#endif

- (id) init;
- (id) initWithType: (int) type countT: (int32_t) countT sales: (double) sales;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int) type;
- (void) setType: (int) type;
#endif
- (BOOL) typeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) countT;
- (void) setCountT: (int32_t) countT;
#endif
- (BOOL) countTIsSet;

#if !__has_feature(objc_arc)
- (double) sales;
- (void) setSales: (double) sales;
#endif
- (BOOL) salesIsSet;

@end

@interface TTGDailyReportForShop : NSObject <TBase, NSCoding> {
  double __unionPay;
  double __mobilePay;
  double __otherPay;
  NSMutableArray * __takeAwayInfoList;
  NSMutableArray * __saleInDayTime;
  NSMutableArray * __saleInWeekTime;
  NSMutableArray * __takeAwayInfoListInDayTime;
  NSMutableArray * __takeAwayInfoListInWeekTime;

  BOOL __unionPay_isset;
  BOOL __mobilePay_isset;
  BOOL __otherPay_isset;
  BOOL __takeAwayInfoList_isset;
  BOOL __saleInDayTime_isset;
  BOOL __saleInWeekTime_isset;
  BOOL __takeAwayInfoListInDayTime_isset;
  BOOL __takeAwayInfoListInWeekTime_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=unionPay, setter=setUnionPay:) double unionPay;
@property (nonatomic, getter=mobilePay, setter=setMobilePay:) double mobilePay;
@property (nonatomic, getter=otherPay, setter=setOtherPay:) double otherPay;
@property (nonatomic, retain, getter=takeAwayInfoList, setter=setTakeAwayInfoList:) NSMutableArray * takeAwayInfoList;
@property (nonatomic, retain, getter=saleInDayTime, setter=setSaleInDayTime:) NSMutableArray * saleInDayTime;
@property (nonatomic, retain, getter=saleInWeekTime, setter=setSaleInWeekTime:) NSMutableArray * saleInWeekTime;
@property (nonatomic, retain, getter=takeAwayInfoListInDayTime, setter=setTakeAwayInfoListInDayTime:) NSMutableArray * takeAwayInfoListInDayTime;
@property (nonatomic, retain, getter=takeAwayInfoListInWeekTime, setter=setTakeAwayInfoListInWeekTime:) NSMutableArray * takeAwayInfoListInWeekTime;
#endif

- (id) init;
- (id) initWithUnionPay: (double) unionPay mobilePay: (double) mobilePay otherPay: (double) otherPay takeAwayInfoList: (NSMutableArray *) takeAwayInfoList saleInDayTime: (NSMutableArray *) saleInDayTime saleInWeekTime: (NSMutableArray *) saleInWeekTime takeAwayInfoListInDayTime: (NSMutableArray *) takeAwayInfoListInDayTime takeAwayInfoListInWeekTime: (NSMutableArray *) takeAwayInfoListInWeekTime;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (double) unionPay;
- (void) setUnionPay: (double) unionPay;
#endif
- (BOOL) unionPayIsSet;

#if !__has_feature(objc_arc)
- (double) mobilePay;
- (void) setMobilePay: (double) mobilePay;
#endif
- (BOOL) mobilePayIsSet;

#if !__has_feature(objc_arc)
- (double) otherPay;
- (void) setOtherPay: (double) otherPay;
#endif
- (BOOL) otherPayIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) takeAwayInfoList;
- (void) setTakeAwayInfoList: (NSMutableArray *) takeAwayInfoList;
#endif
- (BOOL) takeAwayInfoListIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) saleInDayTime;
- (void) setSaleInDayTime: (NSMutableArray *) saleInDayTime;
#endif
- (BOOL) saleInDayTimeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) saleInWeekTime;
- (void) setSaleInWeekTime: (NSMutableArray *) saleInWeekTime;
#endif
- (BOOL) saleInWeekTimeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) takeAwayInfoListInDayTime;
- (void) setTakeAwayInfoListInDayTime: (NSMutableArray *) takeAwayInfoListInDayTime;
#endif
- (BOOL) takeAwayInfoListInDayTimeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) takeAwayInfoListInWeekTime;
- (void) setTakeAwayInfoListInWeekTime: (NSMutableArray *) takeAwayInfoListInWeekTime;
#endif
- (BOOL) takeAwayInfoListInWeekTimeIsSet;

@end

@interface TTGdailyReportForShopRequest_C : NSObject <TBase, NSCoding> {
  double __date;
  NSString * __sid;

  BOOL __date_isset;
  BOOL __sid_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=date, setter=setDate:) double date;
@property (nonatomic, retain, getter=sid, setter=setSid:) NSString * sid;
#endif

- (id) init;
- (id) initWithDate: (double) date sid: (NSString *) sid;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (double) date;
- (void) setDate: (double) date;
#endif
- (BOOL) dateIsSet;

#if !__has_feature(objc_arc)
- (NSString *) sid;
- (void) setSid: (NSString *) sid;
#endif
- (BOOL) sidIsSet;

@end

@interface TTGdailyReportForShopRequest_S : NSObject <TBase, NSCoding> {
  int __state;
  NSString * __message;
  TTGDailyReportForShop * __dailyReportForShop;

  BOOL __state_isset;
  BOOL __message_isset;
  BOOL __dailyReportForShop_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=state, setter=setState:) int state;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, retain, getter=dailyReportForShop, setter=setDailyReportForShop:) TTGDailyReportForShop * dailyReportForShop;
#endif

- (id) init;
- (id) initWithState: (int) state message: (NSString *) message dailyReportForShop: (TTGDailyReportForShop *) dailyReportForShop;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int) state;
- (void) setState: (int) state;
#endif
- (BOOL) stateIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

#if !__has_feature(objc_arc)
- (TTGDailyReportForShop *) dailyReportForShop;
- (void) setDailyReportForShop: (TTGDailyReportForShop *) dailyReportForShop;
#endif
- (BOOL) dailyReportForShopIsSet;

@end

@protocol TTGTTGService <NSObject>
- (TTGdailyReportRequest_S *) dailyReportRequest: (TTGdailyReportRequest_C *) data;  // throws TException
- (TTGdailyRankRequest_S *) dailyRankRequest: (TTGdailyRankRequest_C *) data;  // throws TException
- (TTGdailyReportForShopRequest_S *) dailyReportForShopRequest: (TTGdailyReportForShopRequest_C *) data;  // throws TException
@end

@interface TTGTTGServiceClient : TBaseClient <TTGTTGService> - (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface TTGTTGServiceProcessor : NSObject <TProcessor> {
  id <TTGTTGService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithTTGService: (id <TTGTTGService>) service;
- (id<TTGTTGService>) service;
@end

@interface TTGcxwConstants : NSObject {
}
@end
